[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://mood-commerce.netlify.app"
  NODE_VERSION = "18"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

